---
- name: Ensure docker is installed
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  tags: [Docker]

- name: Enable the Docker service and start it.
  service:
    name: docker.service
    state: started
    enabled: yes
  tags: [Docker]

- name: Copy docker script
  copy:
    src: ./files/plex.sh
    dest: ~/
  tags: [plex]

- name: Execute Plex Docker Container script
  become: yes
  become_method: sudo
  command: bash ~/plex.sh
  tags: [plex]

- name: Remove unneeded packages
  apt:
    autoremove: yes
  retries: 5
